/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dashboard: typeof import('./src/components/dashboard/dashboard.vue')['default']
    JobItem: typeof import('./src/components/ai/JobItem.vue')['default']
    MissionItem: typeof import('./src/components/point/MissionItem.vue')['default']
    RecordItem: typeof import('./src/components/point/RecordItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    WithdrawDialog: typeof import('./src/components/point/WithdrawDialog.vue')['default']
  }
}
