spring:
  application:
    name: caicai-new-feature-backend
  data:
    redis:
#      host: ${REDIS_HOST:120.25.120.221}
#      port: 6379
#      password: ccN.8888
      host: ${REDIS_HOST:39.108.130.61}
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 20
          max-idle: 10
          max-wait: 10000
          min-idle: 5
  ai:
    openai:
      api-key: sk-9ab46081d9a749269584d1fc330bab12 #公司的API-Key
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-plus # qwen-plus
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1536
    vectorstore:
      redis:
        initialize-schema: true
        index: caicai_posts_vector_idx
        prefix: "caicai:post:"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #待配置
    time-zone: GMT+8
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
#    TODO 记得切换
#     url: jdbc:mysql://192.168.2.185:3306/caicai # 测试的数据库的地址 开发环境时使用
#     url: jdbc:mysql://${MYSQL_HOST:120.25.120.221}:${MYSQL_PORT:3307}/ccn_db # 生产环境请使用
     url: jdbc:mysql://127.0.0.1:3306/caicai
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: root
#    TODO 记得切换
     password: 123456 # 开发环境时的密码
#     password: ccN.8888 # 生产环境时使用密码
  servlet:
    multipart:
      max-file-size: 30MB
      enabled: true
      max-request-size: 30MB
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #转驼峰

server:
  port: 9080


jwt:
  secret: django-insecure-6w4@kkj13#9u0&#(7%5i*_4a45kp46jomm8f-2h3)b9qzmgjmr
  expiration: 3600000
  token-prefix: 'Bearer '

aliyun:
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tBSyY2sXK8B8fjdzLrH
    access-key-secret: RfT7Cl3NYQMoS6RYRNZJvAFq0M6Ah4
    bucket-name: ccn-bucket
    access-url:  https://ccn-bucket.oss-cn-guangzhou.aliyuncs.com

logging:
  level:
    sql: warn
  file:
    path: classpath:ccn_sql.log